apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test
  name: junior-test-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get","list","watch","create","update","patch","delete"]

