apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: production
  name: senior-production-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list","watch","create","delete","update","patch"]
