apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: senior-production-rolebinding
  namespace: production
subjects:
- kind: Group
  name: senior
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: senior-production-role
  apiGroup: rbac.authorization.k8s.io
