apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: senior-test-rolebinding
  namespace: test
subjects:
- kind: Group
  name: senior
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: senior-test-role
  apiGroup: rbac.authorization.k8s.io
