apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test
  name: senior-test-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list","watch","create","delete","update","patch"]
  
